/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class amber_os_OpenFileDialog */

#ifndef _Included_amber_os_OpenFileDialog
#define _Included_amber_os_OpenFileDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     amber_os_OpenFileDialog
 * Method:    showNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_amber_os_OpenFileDialog_showNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
