/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class amber_os_OS */

#ifndef _Included_amber_os_OS
#define _Included_amber_os_OS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     amber_os_OS
 * Method:    nativeGetFont
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_amber_os_OS_nativeGetFont
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
