/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class amber_os_Win */

#ifndef _Included_tk_amberide_ide_os_Win
#define _Included_tk_amberide_ide_os_Win
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     amber_os_Win
 * Method:    nativeGetFont
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tk_amberide_ide_os_Win_nativeGetFont
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
