/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tk_amberide_ide_os_filechooser_WinFileDialog */

#ifndef _Included_tk_amberide_ide_os_filechooser_WinFileDialog
#define _Included_tk_amberide_ide_os_filechooser_WinFileDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tk_amberide_ide_os_filechooser_WinFileDialog
 * Method:    showNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tk_amberide_ide_os_filechooser_WinFileDialog_showNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
