/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tk_amberide_ide_os_colorpicker_WinColorDialog */

#ifndef _Included_tk_amberide_ide_os_colorpicker_WinColorDialog
#define _Included_tk_amberide_ide_os_colorpicker_WinColorDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tk_amberide_ide_os_colorpicker_WinColorDialog
 * Method:    showNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tk_amberide_ide_os_colorpicker_WinColorDialog_showNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
