package amber.gui.dialogs;

import amber.Amber;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.io.File;

/**
 * @author Tudor
 */
public class ExportImageDialog extends javax.swing.JDialog {

    private JFileChooser browser = new JFileChooser("Export image as...");

    /**
     * Creates new form ExportImageDialog
     */
    public ExportImageDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();

        browser.addChoosableFileFilter(new FileFilter() {
            private final String[] imgExt = new String[]{"jpg", "png", "gif"};

            @Override
            public boolean accept(File file) {
                for (String extension : imgExt) {
                    if (file.getName().toLowerCase().endsWith(extension)) {
                        return true;
                    }
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "Image files (*.jpg, *.png, *.gif)";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationGroup = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        optionGroup = new javax.swing.JPanel();
        currentLayerBox = new javax.swing.JCheckBox();
        currentZoomBox = new javax.swing.JCheckBox();
        drawGridBox = new javax.swing.JCheckBox();
        formatLabel = new javax.swing.JLabel();
        formatComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("amber/Bundle"); // NOI18N
        setTitle(bundle.getString("ExportImageDialog.title")); // NOI18N
        setModal(true);
        setResizable(false);

        locationGroup.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ExportImageDialog.locationGroup.border.title"))); // NOI18N

        nameLabel.setText(bundle.getString("ExportImageDialog.nameLabel.text")); // NOI18N

        browseButton.setText(bundle.getString("ExportImageDialog.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout locationGroupLayout = new javax.swing.GroupLayout(locationGroup);
        locationGroup.setLayout(locationGroupLayout);
        locationGroupLayout.setHorizontalGroup(
            locationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        locationGroupLayout.setVerticalGroup(
            locationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationGroupLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(locationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(locationGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton))
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        optionGroup.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ExportImageDialog.optionGroup.border.title"))); // NOI18N

        currentLayerBox.setText(bundle.getString("ExportImageDialog.currentLayerBox.text")); // NOI18N

        currentZoomBox.setSelected(true);
        currentZoomBox.setText(bundle.getString("ExportImageDialog.currentZoomBox.text")); // NOI18N

        drawGridBox.setText(bundle.getString("ExportImageDialog.drawGridBox.text")); // NOI18N
        drawGridBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawGridBoxActionPerformed(evt);
            }
        });

        formatLabel.setText(bundle.getString("ExportImageDialog.formatLabel.text")); // NOI18N

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNG", "GIF", "JPEG" }));

        javax.swing.GroupLayout optionGroupLayout = new javax.swing.GroupLayout(optionGroup);
        optionGroup.setLayout(optionGroupLayout);
        optionGroupLayout.setHorizontalGroup(
            optionGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionGroupLayout.createSequentialGroup()
                        .addComponent(formatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(optionGroupLayout.createSequentialGroup()
                        .addGroup(optionGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentLayerBox)
                            .addComponent(currentZoomBox)
                            .addComponent(drawGridBox))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionGroupLayout.setVerticalGroup(
            optionGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionGroupLayout.createSequentialGroup()
                .addGroup(optionGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatLabel)
                    .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(currentLayerBox)
                .addGap(0, 0, 0)
                .addComponent(currentZoomBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawGridBox)
                .addContainerGap())
        );

        saveButton.setText(bundle.getString("ExportImageDialog.saveButton.text")); // NOI18N
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("ExportImageDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optionGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(6, 6, 6)
                        .addComponent(cancelButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locationGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(optionGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        if (browser.showSaveDialog(Amber.getUI()) == JFileChooser.APPROVE_OPTION) {
            locationField.setText(browser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void drawGridBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawGridBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drawGridBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox currentLayerBox;
    private javax.swing.JCheckBox currentZoomBox;
    private javax.swing.JCheckBox drawGridBox;
    private javax.swing.JComboBox formatComboBox;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JTextField locationField;
    private javax.swing.JPanel locationGroup;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel optionGroup;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
